# Análise Exploratória

Teste explorando dados históricos

In [1]:
import pandas as pd
import pyarrow as pa

In [7]:
arquivo = "../data/raw/megasena/resultados.parquet.gzip"
df = pd.read_parquet(arquivo)

df.shape

(2549, 32)

In [6]:
df.head()

,acumulado,dataApuracao,dataProximoConcurso,dezenasSorteadasOrdemSorteio,exibirDetalhamentoPorCidade,id,indicadorConcursoEspecial,listaDezenas,listaDezenasSegundoSorteio,listaMunicipioUFGanhadores,...,tipoJogo,tipoPublicacao,ultimoConcurso,valorArrecadado,valorAcumuladoConcurso_0_5,valorAcumuladoConcursoEspecial,valorAcumuladoProximoConcurso,valorEstimadoProximoConcurso,valorSaldoReservaGarantidora,valorTotalPremioFaixaUm
0,True,17/12/2022,31/12/2022,"[30, 10, 33, 01, 06, 35]",True,None,1,"[01, 06, 10, 30, 33, 35]",None,[],...,MEGA_SENA,3,True,42439333.5,1.735093e+08,1.735093e+08,1.735093e+08,500000000.0,0.0,0.0
1,False,14/12/2022,17/12/2022,"[25, 23, 29, 30, 09, 15]",True,None,1,"[09, 15, 23, 25, 29, 30]",None,"[{'ganhadores': 1, 'municipio': 'CANAL ELETRON...",...,MEGA_SENA,3,True,117895720.5,3.008841e+07,1.354364e+08,0.000000e+00,3000000.0,0.0,0.0
2,True,10/12/2022,14/12/2022,"[37, 10, 38, 25, 31, 57]",True,None,1,"[10, 25, 31, 37, 38, 57]",None,[],...,MEGA_SENA,3,True,114072727.5,2.221781e+07,1.336476e+08,1.222898e+08,135000000.0,0.0,0.0
3,True,07/12/2022,10/12/2022,"[34, 03, 48, 28, 23, 38]",True,None,1,"[03, 23, 28, 34, 38, 48]",None,[],...,MEGA_SENA,3,True,109551649.5,1.460243e+07,1.319168e+08,1.101744e+08,125000000.0,0.0,0.0
4,True,03/12/2022,07/12/2022,"[57, 36, 32, 39, 20, 23]",True,None,1,"[20, 23, 32, 36, 39, 57]",None,[],...,MEGA_SENA,3,True,109181808.0,7.288868e+06,1.302546e+08,9.853918e+07,115000000.0,0.0,0.0